CC=gcc
CFLAGS=-ansi -pedantic-errors -Wall

# mettere una regola che compili tutto



termination: Termination.c info.h
	${CC} -c Termination.c ${CFLAGS} -o termination.o
	gcc termination.o error.o
	
